version: '3.8'

services:
  app:
    build: .
    container_name: face_api_app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=face_api
      - PGPORT=5432

  db:
    image: postgres:17
    container_name: face_api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: face_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vector"]

volumes:
  postgres_data: